version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: overpower_user
      MYSQL_PASSWORD: overpower_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"