name: Node.js Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
        COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
    strategy:
      matrix:
        node-version: [14.x]

    services:
      mysql:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: postgres_pass
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
